# Taller 3 - Factorización A=QR 
### Método de ortogonalización de Gram-Schmidt



El método de Gram-Schmidt se usa para hallar bases ortogonales (Espacio Euclideo no normalizado) de cualquier 
base no euclídea.

En primer lugar tenemos que:

$$\mathbf{v}-{\langle \mathbf{v}, \mathbf{u}\rangle\over\langle \mathbf{u}, \mathbf{u}\rangle}\mathbf{u} = \mathbf{v} - \mathrm{proy}_{\mathbf{u}}\,(\mathbf{v})$$

Es un vector ortogonal a $\mathbf{u}$. Entonces, dados los vectores $\mathbf{v}_1, \dots, \mathbf{v}_n$ , se define:

 $$\mathbf{u}_1 = \mathbf{v}_1,$$

$$\mathbf{u}_2 = \mathbf{v}_2-{\langle \mathbf{v}_2, \mathbf{u}_1\rangle\over\langle\mathbf{u}_1,\mathbf{u}_1\rangle}\mathbf{u}_1, $$

$$\mathbf{u}_3 = \mathbf{v}_3-{\langle \mathbf{v}_3, \mathbf{u}_1\rangle\over\langle\mathbf{u}_1,\mathbf{u}_1\rangle}\mathbf{u}_1-{\langle \mathbf{v}_3, \mathbf{u}_2\rangle\over\langle\mathbf{u}_2,\mathbf{u}_2\rangle}\mathbf{u}_2, $$

Generalizando en k:

$$\mathbf{u}_k = \mathbf{v}_k-\sum_{j=1}^{k-1}{\langle \mathbf{v}_k, \mathbf{u}_j\rangle\over\langle\mathbf{u}_j,\mathbf{u}_j\rangle}\mathbf{u}_j $$


A partir de las propiedades del producto escalar, es sencillo probar que el conjunto de vectores $\mathbf{u}_1, \dots, \mathbf{u}_n$ es ortogonal.



### Ejemplo
Si se considera la descomposición de
$$A = 
\left( \begin{matrix}
12 & -51 & 4 \\
6 & 167 & -68 \\
-4 & 24 & -41 
\end{matrix} \right)
.$$

Se busca la matriz ortogonal $Q$ tal que
$$
\begin{matrix}
 Q\,Q^{T} = I.
\end{matrix}
$$

Por lo que calculamos $Q$ mediante Gram-Schmidt como sigue:
$$
U = 
\left( \begin{matrix}
\mathbf u_1 & \mathbf u_2 & \mathbf u_3
\end{matrix} \right)
=
\left( \begin{matrix}
12 & -69 & -58/5 \\
6  & 158 & 6/5 \\
-4 &  30 & -33 
\end{matrix} \right);
$$

$$
Q = 
\left( \begin{matrix}
\frac{\mathbf u_1}{\|\mathbf u_1\|} & 
\frac{\mathbf u_2}{\|\mathbf u_2\|} & 
\frac{\mathbf u_3}{\|\mathbf u_3\|}
\end{matrix} \right)
=
\left( \begin{matrix}
     6/7    &    -69/175   &   -58/175   \\
     3/7    &    158/175   &    6/175   \\
    -2/7    &      6/35    &   -33/35    
\end{matrix} \right);
$$

Por lo tanto, tenemos
$$
 A = QQ^{T}A = Q R; 
$$

$$
 R = Q^{T}A =
\left( \begin{matrix}
    14  &  21          &            -14 \\
     0  & 175          &            -70 \\
     0  &   0          &             35
\end{matrix} \right).
$$

## Programación del método

In [1]:
import numpy as np 
import numpy.linalg as npl

In [2]:
def GramSchmidt(V):
    m=V.shape[0]
    n=V.shape[1]
    U=np.zeros((m,n))
    U[0]=np.copy(V[0])
    for k in range(1,m):
        U[k]=np.copy(V[k])
        for j in range(k):
            U[k]=U[k]-((np.dot(V[k],U[j]))/(npl.norm(U[j])**2))*U[j]
#Los vectores columna de U ya son ortogonales entre si.
#Ahora normalizamos cada vector columna de U para obtener una matriz ortonormal.
    Q=np.zeros((m,n))
    for k in range (m):
        Q[k]=U[k]/npl.norm(U[k])
    return Q

In [4]:
#Definimos una matriz V compuesta de vectores columna no ortogonales entre si.
#Usemos la misma matriz del taller de Hause-Holder para comparar resultados.
V=np.array([[12,6,-4],[-51,167,24],[4,-68,-41]])
print("V=",V)
m=V.shape[0]
print("Número de filas m = ",m)
n=V.shape[1]
print("Número de columnas n = ",n)

V= [[ 12   6  -4]
 [-51 167  24]
 [  4 -68 -41]]
Número de filas m =  3
Número de columnas n =  3


In [77]:
#Introducimos la matriz que acabamos de definir en la función 
#para ortogonalizar de acuerdo al método de Gramm-Schmidt.
Q=GramSchmidt(V)
print("Q=",Q.T)

Q= [[ 0.85714286 -0.39428571 -0.33142857]
 [ 0.42857143  0.90285714  0.03428571]
 [-0.28571429  0.17142857 -0.94285714]]


In [72]:
#Verificamos las propiedades de ortogonalidad de la matriz resultante.
detQ=np.round(npl.det(Q),2)
print(detQ)

-1.0


In [73]:
#Si el determinante de la matriz es 1 o -1, la inversa es igual a la transpuesta.
np.round(npl.inv(Q),2)==np.round(Q.T,2)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [75]:
#El producto interior entre los vectores columna ortogonalizados tiene que ser cero.
#La resolución de la computadora nos dará un número muy pequeño, prácticamente cero.
np.dot(U[0],U[1])

2.7755575615628914e-16