# Taller 2 - Factorización A=QR 
### Método de reflexiones de Hause-Holder
(Fuente: https://es.wikipedia.org/wiki/Factorizaci%C3%B3n_QR)

La factorización QR de una matriz es una descomposición de una matriz como producto de una matriz ortogonal por una matriz triangular superior triangular superior. La descomposición QR es la base del algoritmo QR utilizado para el cálculo de los valores y vectores propios de una matriz.




Una $\textbf{transformación de Householder}$ o reflexión de Householder es una transformación que refleja el espacio con respecto a un plano determinado. Esta propiedad se puede utilizar para realizar la transformación QR de una matriz si tenemos en cuenta que es posible elegir la matriz de Householder de manera que un vector elegido quede con una única componente no nula tras ser transformado (es decir, premultiplicando por la matriz de Householder). Gráficamente, esto significa que es posible reflejar el vector elegido respecto de un plano de forma que el reflejo quede sobre uno de los ejes de la base cartesiana.

La manera de elegir el plano de reflexión y formar la matriz de Householder asociada es el siguiente:

Sea $\mathbf{x}$ un vector columna arbitrario m-dimensional tal que ||$\mathbf{x}$|| = |$\alpha$|, donde $\alpha$ es un escalar.

Entonces, siendo $\mathbf{e}_1$ el vector $(1,0,...,0)^T$, y ||$\cdot$|| la norma euclídea, se define:

$$ \mathbf{u} = \mathbf{x} - \alpha\mathbf{e}_1,$$
$$ \mathbf{v} = \frac{\mathbf{u}}{||\mathbf{u}||},$$
$$ Q = I - 2 \mathbf{v}\mathbf{v}^T.$$

$v$ es un vector unitario perpendicular al plano de reflexión elegido.
$Q$ es una matriz de Householder asociada a dicho plano.

$$ Qx = (\alpha, 0, \cdots, 0)^T.$$

Esta propiedad se puede usar para transformar gradualmente los vectores columna de una matriz $A$ de dimensiones $m$ por $n$ en una matriz $\textit{triangular superior}$. En primer lugar se multiplica $A$ con la matriz de Householder $Q_1$ que obtenemos al elegir como vector $\mathbf{x}$ la primera columna de la matriz. Esto proporciona una matriz $QA$ con ceros en la primera columna (excepto el elemento de la primera fila).

$$Q_{1}A = \left[ \begin{matrix}
                   \alpha_1&\star&\dots&\star\\
                      0    &     &     &    \\
                   \vdots  &     &  A' &    \\
                      0    &     &     & \end{matrix}\right]$$

el procedimiento se puede repetir para $A'$ (que se obtiene de $A$ eliminando la primera fila y columna), obteniendo así una matriz de Householder $Q_2$. Hay que tener en cuenta que $Q_2$ es menor que $Q_1$. Para conseguir que esta matriz opere con $Q_1A$ en lugar de $A$. Es necesario expandirla hacia arriba a la izquierda, completando con un uno en la diagonal, o en general:

$$Q_k = \left(\begin{matrix}
                  I_{k-1} & 0\\
                   0  & Q_k'\end{matrix} \right).$$

Tras repetir el proceso $t$ veces, donde $ t = min(m - 1, n)$, 
$$ R = Q_t \cdots Q_2Q_1A $$
es una matriz triangular superior. De forma que tomando
$$Q = Q_1 Q_2 \cdots Q_t$$

$A = Q^T R$ es una descomposición $QR$ de la matriz $A$. 

Este método tiene una estabilidad numérica mayor que la del método de Gram-Schmidt. 


### Ejemplo 
Vamos a calcular la descomposición de la matriz
$$A =  \left(\begin{matrix}
12 & -51 & 4 \\
6 & 167 & -68 \\
-4 & 24 & -41 \end{matrix} \right) .$$

En primer lugar necesitamos encontrar una reflexión que transforme la primera columna de la matriz ''A'', vector $\mathbf{a}_1 = (12, 6, -4)^T$, en $\|\mathbf{a}_1\| \;\mathrm{e}_1 = (14, 0, 0)^T.$ 

usando la expresión, 
$$\mathbf{u} = \mathbf{a}_1 - \alpha\mathbf{e}_1,$$
y 
$$\mathbf{v} = {\mathbf{u} \over |\mathbf{u} |},$$

en nuestro caso :
$$\alpha = 14  \text{   y   }  \mathbf{a}_1 = (12, 6, -4)^T$$

Por lo tanto
$$\mathbf{u} = (-2, 6, -4)^T \text{   y   } \mathbf{v} = \frac{2}{\sqrt{14}}(-1, 3, -2)^T,$$

entonces

$$Q_1 = I - \frac{2}{\sqrt{14}\sqrt{14}} 
\left(\begin{matrix} -1 \\ 3 \\ -2 \end{matrix} \right)\left(\begin{matrix} -1 & 3 & -2 \end{matrix} \right)$$

$$ = I - \frac{1}{7}\left(\begin{matrix}
1 & -3  & 2 \\
-3 & 9 & -6 \\
2  & -6  & 4 
\end{matrix} \right)
 = \left(\begin{matrix}
6/7 & 3/7   &  -2/7 \\
3/7  &-2/7  &  6/7 \\
-2/7 & 6/7  &   3/7 \\
\end{matrix} \right).$$

Ahora observamos:
$$Q_1A = \left(\begin{matrix}
14 & 21 & -14 \\
0 & -49 & -14 \\
0 & 168 & -77 \end{matrix} \right),$$
con lo que ya casi tenemos una matriz triangular. Sólo necesitamos hacer cero en el elemento (3,2).

Tomando la submatriz bajo el (1, 1) y aplicando de nuevo el proceso a
$$A' = M_{11} = \left(\begin{matrix}
-49 & -14 \\
168 & -77 \end{matrix} \right).$$
Mediante el mismo método que antes obtenemos la matriz de Householder
$$Q_2 = \left(\begin{matrix}
1 & 0 & 0 \\
0 & -7/25 & 24/25 \\
0 & 24/25 & 7/25 \end{matrix} \right)$$

Finalmente obtenemos
$$Q=Q_1Q_2=\left(\begin{matrix}
6/7 & -69/175 & -58/175\\
3/7 & 158/175 & 6/175 \\
-2/7 & 6/35 & -33/35
\end{matrix} \right) $$
$$R=Q^\top A=\left(\begin{matrix}
14 & 21 & -14 \\
0 & 175 & -70 \\
0 & 0 & 35
\end{matrix} \right).$$
La matriz ''Q'' es ortogonal y ''R'' es triangular superior, de forma que ''A'' = ''QR'' es la descomposición QR buscada.


## Programación del método

In [1]:
import numpy as np 
import numpy.linalg as npl

In [ ]:
#Definimos la matriz a factorizar.
A = np.array([[12,6,-4],[-51,167,24],[4,-68,-41]])
print("Matriz A: \n",A.T)

In [11]:
def householderQR(A):
    m=A.shape[0]
    n=A.shape[1]
    R=np.copy(A)
    Q=np.identity(m)
    for i in range (n):
        vk=np.copy(R[:,i])
        q=0
        while q<i:
            vk[q]=0
            q=q+1
        vk[i]=vk[i]+npl.norm(vk)*np.sign(vk[q])
        vk = np.transpose(np.array([vk]))
        Hk = np.identity(m)-2*vk*np.transpose(vk)/npl.norm(vk)**2
        R= np.dot(Hk,R)
        Q = np.dot(Hk,Q)
    Q=npl.inv(Q)
    return(Q,R)

In [30]:
Q,R=householderQR(A.T)
print("\n Matriz ortogonal Q: \n",np.round(Q,3))
print("\n\n Matriz triangular superior R: \n",np.round(R,2))


 Matriz ortogonal Q: 
 [[-0.857  0.394 -0.331]
 [-0.429 -0.903  0.034]
 [ 0.286 -0.171 -0.943]]


 Matriz triangular superior R: 
 [[ -14.  -21.   14.]
 [  -0. -175.   70.]
 [   0.    0.   35.]]


### Verificación de ortogonalidad con propiedades de matrices.

In [35]:
R=np.matmul(Q.T,A.T)
print(np.round(R,2))

[[ -14.  -21.   14.]
 [  -0. -175.   70.]
 [   0.    0.   35.]]


In [32]:
Qinv=np.round(npl.inv(Q),2)
Qtrans=np.round(Q.T,2)
Qtrans==Qinv

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [33]:
np.round(npl.det(Q))

-1.0